server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlite:./prisma/dev.db}
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
      pool-name: sqlite-hikari
  jackson:
    serialization:
      write-dates-as-timestamps: false
    mapper:
      accept-case-insensitive-enums: true
    default-property-inclusion: non_null

logging:
  level:
    root: INFO
    org.springframework.web: INFO
