name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: npx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      # Setup Java for Kotlin backend
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Setup Python for Django backend
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Install uv for Django backend
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      # Setup pnpm
      - uses: pnpm/action-setup@v3
        with:
          version: 10

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      # Generate Prisma Client
      - run: pnpm prisma:generate

      - run: npx playwright install --with-deps

      # Install Python dependencies for Django backend
      - name: Install Django dependencies
        run: uv sync
        working-directory: apps/django-backend

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: npx nx-cloud record -- echo Hello World
      # When you enable task distribution, run the e2e-ci task instead of e2e
      - run: npx nx run-many -t lint test build typecheck e2e
      # Nx Cloud recommends fixes for failures to help you get CI green faster. Learn more: https://nx.dev/ci/features/self-healing-ci
      - run: npx nx fix-ci
        if: always()
